stack: kuujakke/arkisto
version: 0.0.2
services:
  web:
      image: jwilder/nginx-proxy:alpine
      environment:
        - KONTENA_LB_MODE=http
        - KONTENA_LB_BALANCE=roundrobin
        - KONTENA_LB_INTERNAL_PORT=80
      links:
        - network/lb
        - app
        - redis
  db:
    image: arkisto-db:latest
    build:
      context: .
      dockerfile: config/containers/Dockerfile-postgres

  app:
    image: arkisto-app:latest
    build:
      context: .
      dockerfile: Dockerfile

  redis:
    image: redis/alpine
    ports:
      - '6379:6379'
    volumes:
      - arkisto_redis:/var/lib/redis/data

  sidekiq:
    image: arkisto-sidekiq:latest
    build: .
    command: bundle exec sidekiq -C config/sidekiq.yml
    links:
      - db
      - redis
    volumes:
      - arkisto_app:/arkisto

volumes:
  arkisto_app:
    external:
      name: app
  arkisto_redis:
    external:
      name: redis
  arkisto_db:
    external:
      name: db