default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  username: pguser
  password: password

development:
  <<: *default
  database: arkisto_development

test:
  <<: *default
  database: arkisto_test

production:
  <<: *default
  database: arkisto_production
