FROM onjin/alpine-postgres:latest

RUN apk add --no-cache git build-base && \
    cd /usr/local && \
    git clone https://github.com/eulerto/pg_similarity.git && \
    cd pg_similarity && \
    USE_PGXS=1 make && \
    USE_PGXS=1 make install && \
    apk del git build-base && \
    rm -rf /var/cache/apk/*

COPY config/containers/pg-similarity.sql /docker-entrypoint-initdb.d

EXPOSE 5432
